### ISSUE TITLE
Image viewer command line arguments

### ISSUE THREAD

**Issue by outpaddling** [trueos/lumina#240]
Is it necessary for Insight to prefix filenames with file:/// when launching an image viewer?

This is the command invoked when I click on a jpeg:

28885  -  S        0:00.32 /usr/local/bin/qiviewer file:///usr/home/bacon/green.jpg

I'm patching qiviewer to support this, but I suspect other image viewers will choke on it as well.

Cheers,

    Jason

**Comment by beanpole135** [comment]
Jason, the "file://" prefix is only used by lumina-open when the application specifically requests URL syntax for inputs. This sounds like the .desktop app registration for qiviewer is mistakenly using the "%U" or "%u" wildcards (URL syntax) within the "Exec=" line rather than the "%F" or "%f" wildcards (File syntax) - and should be fixed upstream within the qiviewer app itself.
