### ISSUE TITLE
Desktop, contextual menu, Preferences, Desktop: does not bring the required application to the front

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#249]
I set QTerminal as the preferred virtual terminal, then launched QTerminal. 

I used the contextual menu for desktop preferences. 

**Expected**

_Default Applications_ should come to the front. 

**Actual result**

QTerminal remains in front. 

Also there's an apparently endless asynchronous progress indicator over the cursor, I don't know whether that's a hangover from https://github.com/trueos/lumina/issues/248

**Comment by beanpole135** [comment]
The "endless asynchronous progress indicator" is the desktop waiting for a new window to appear after you told it to launch something. This typically happens if the app you tried to launch crashes before opening a window or fails to launch altogether (such as the case of your empty default terminal setting in #248). 
I will add some better error checking/handling to lumina-open here soon so that you get a warning dialog if the app fails to launch (which will also stop the "pending" mouse cursor).

As for the window order, that is a Fluxbox thing. It is usually really good about ensuring the newest window gets put on the top, and if qterminal took longer to open than lumina-config (which is very likely), the I can understand why the qterminal window appeared on top (it was created after the lumina-config window).

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/lumina/commit/ca2af75002ff5e88aebe8026e915e71d6a17c498
