### ISSUE TITLE
index.theme file makes linux apps crash

### ISSUE THREAD

**Issue by chrisvs** [trueos/lumina#255]
For some reason, lumina leaves a file ~/.icons/default/index.theme behind that causes other DE's installed on the same machine to become unstable. The content of the file shows that the cursor theme inherits from default, itself thus.

Tested on Arch Linux wiht linux kernel 4.7.1.
The issue is described on the Arch Forum :

[https://bbs.archlinux.org/viewtopic.php?id=215758]

Even lumina itself becomes unresponsive because of this. After installing and logging in (and customizing the interface), I logged out and tried to re-login and I could not.

**Comment by beanpole135** [comment]
Interesting - the contents of that file do not appear to be set by Lumina in this case.
Lumina sets ~/.icon/default/index.theme to "Inherits=<some other theme>", and never "default" (since there should not be a cursor theme called "default" on the system - at least there is not on BSD systems) .

Just in case, I just added a check to Lumina to remove the ~/.icon/default/index.theme file if a theme called "default" is selected by the user - this should at least prevent this kind of foot-shooting from occuring. (also backported to the qt5/1.0.0 branch)

https://github.com/trueos/lumina/commit/e7442fa963efa09497877dcb9efe1fd61963624e
