### ISSUE TITLE
lumina-textedit can't find icons when run under sudo

### ISSUE THREAD

**Issue by utrenkner** [trueos/lumina#273]
When starting lumina-textedit with sudo (and only then), I get the following error messages, and the interface looks degraded:
```
Could not find icon: "document-edit" ""
Could not find icon: "application-exit" ""
Could not find icon: "document-new" ""
Could not find icon: "document-open" ""
Could not find icon: "document-close" ""
Could not find icon: "document-save" ""
Could not find icon: "document-save-as" ""
Could not find icon: "edit-find" ""
Could not find icon: "edit-find-replace" ""
Could not find icon: "format-text-color" ""
Could not find icon: "format-fill-color" ""
Could not find icon: "go-down-search" ""
Could not find icon: "go-up-search" ""
Could not find icon: "format-text-italic" ""
Could not find icon: "arrow-down" ""
Could not find icon: "arrow-down-double" ""
Could not find icon: "format-fill-color" ""
Could not find icon: "dialog-cancel" ""
Could not find icon: "dialog-ok" ""
Could not find icon: "format-fill-color" ""
```
Do you know what I need to do to make them show up also with `sudo`?

**Comment by beanpole135** [comment]
That sounds like sudo is stripping out one of the main environment variables (probably XDG_DATA_DIRS). Try running "sudo env" and see if any of the XDG_* environment variables are there or not. If not, you can modify your sudo rules to leave particular env variables alone. The two I would recommend are XDG_DATA_DIRS, XDG_CONFIG_DIRS, and PATH (the XDG_*_HOME variables are specific for your user - don't pass those through otherwise you will end up with root-permissioned files in your users home dir).

Meanwhile, I will see what I can do within the lumina tools themselves to automatically detect when those env variables are missing and automatically regenerate them.

**Comment by utrenkner** [comment]
Thanks, Ken @beanpole135 !

I added this to my sudoers file and it works:`Defaults env_keep += "XDG_DATA_DIRS XDG_CONFIG_DIRS"`

I could not find any difference between including PATH or not. Therefore, I left it out. There is still a minimal issue with the fonts - it uses a rather ugly default font when running as sudo. But compared to the icons this is rather irrelevant.

Many thanks for the quick solution.

**Comment by beanpole135** [comment]
I just fixed the auto-detection of this as well. Now it should not matter if sudo strips the environment or not - each tool will do a quick check/fix of the `XDG_*`at startup for their process.

https://github.com/trueos/lumina/commit/13f244c54d69fdb857ccd317a16d2cdf0bc80c09
