### ISSUE TITLE
Fedora packages

### ISSUE THREAD

**Issue by rapgro** [trueos/lumina#283]
Hi,
I hereby proudly inform about official packages in the Fedora and in EPEL7 stable repositories.
You can remove the section about copr [1] from the homepage. It's now sufficient to just call as root without any additional repository needed: `dnf install lumina-desktop`
The desktop applications have their own subpackages each. For instance, to install lumina-fm:
`dnf install lumina-fm`
Also, there should be no need in Fedora to build from source. Please be aware that the packages are not yet in Fedora 23 but requested.

[1] https://lumina-desktop.org/get-lumina/#fedora

**Comment by beanpole135** [comment]
Website updated!
I left the building from source section in since that is still the fallback method for versions of Fedora where the package is not available (such as 23 at the moment). We can go through and clean that out later on once some time has elapsed and the packages are in all the various repositories.

Thanks again!
