### ISSUE TITLE
Feature UI idea for Lumina-DE

### ISSUE THREAD

**Issue by jaypatelani** [trueos/lumina#303]
Hello,

This is some idea i thought for lumina
![homepage-64472171-1479481832](https://cloud.githubusercontent.com/assets/17174485/20435720/3104ef3a-add3-11e6-95a2-4d8860ba29ce.png)
. : http://imgur.com/a/pHVIX 
-->common status bar in bottom to save extra empty panel space.. even if application window is resized status bar can be there at bottom only so no unused or empty spaces in between notification area and lumina app menu button.
--> All app menu can be same like Mac-OS like. 
--> all open apps or app icons can be on left where we can also have notification on app icon it self. eg. on Thunderbird we can see number showing emails unread.etc
--> we can have all widgets on right side workspace which we can call in front of with shortcuts. eg. when need sticky notes we can call it when surfing internet using some key bindings. 

Not sure is this is possible.

Regards,
Jay

**Comment by jaypatelani** [comment]
App icons == docker . sorry if English not good.

**Comment by q5sys** [comment]
It might be a better idea to simply add more functionality into the system tray, rather than running an additional application to act as a dock which can be overlayed onto the screen.  If you really need this functionality before we can implement something, there are several programs that can accomplish this.  Cairo-Dock comes to mind, but I've never tried to use it on anything other than Linux.

**Comment by jaypatelani** [comment]
@q5sys is there a way to get opened applications on task bar to just show icon rather with while title?

**Comment by q5sys** [comment]
you would have to edit the source code to change the way the task bar works.

**Comment by beanpole135** [comment]
Actually, if you switch your task manager plugin to the standard version (grouped windows), then they just show up as icons on the taskbar *unless* there is no icon specified by the window for some reason.

**Comment by beanpole135** [comment]
Commenting on the rest of the feature request:
The bottom panel and left-hand app panel are both completely possible to do within Lumina *right now*. The top panel is highly "Mac-like" and not really possible at the moment due to the differences in how the window system works on X compared to Mac's Cocoa display system. Within X (which almost all Linux/BSD systems use) the desktop and/or window manager is often using a completely different graphical toolkit from the applications (GTK 2/3, Qt 3/4/5, motif, EFL, etc....) - so the only things which are possible to use are the information declared via the ICCCM/EWMH specifications for window information (cross-toolkit specification). Unfortunately, the window menu bar's are not governed by the specs, so the WM/DE cannot "see" that information from a given window.

**Comment by jaypatelani** [comment]
Thanks.. I managed to get it to work like i wanted..
