### ISSUE TITLE
Lumina Screenshot fails to forewarn the user when discarding unsaved data

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#310]
This issue was initially observed when, working as user 'test', I used the _Save As_ button to supposedly save to a directory that is owned by a different user ('bbsadmin-l'): 

```
$ ls -dl /usr/home/bbsadmin-l/Public
drwxr-xr-x  2 bbsadmin-l  bbsadmin-l  3 20 Nov 09:06 /usr/home/bbsadmin-l/Public
$ 
```

The loss of data was not realised until after the user had logged out, so I logged in and made the issue reproducible in another way. 

## Steps

1. launch Lumina Screenshot
2. observe the window of the application
3. log out

## Expected

- either (a) a prompt to save data; or (b) automated save to a nonvolatile area of the file system

## Actual result

- without warning, loss of data.

## Alternative steps to dataloss

1. launch Lumina Screenshot
2. key Escape.

## Thought

If (b) is acceptable then I suggest either of these formats –

`~/Pictures/yyyy-MM-dd-hh-mm-ss screenshot.png`

`~/Pictures/yyyy-MM-dd hh-mm-ss screenshot.png`

– of the two, the second format will probably be easier on the eye if, over time, the user allows an 'automated collection of shots' to become large.

**Comment by q5sys** [comment]
A) I dont know if it really makes sense to prompt the user to save.  Once a
user makes a screenshot they are ~instantly~ presented with the option to
save.  If they decide not to, why should the application pester them again
to do it?  I'd get annoyed rather fast if everytime I wanted to shut down
the application without saving (intentionally), it wanted to prompt me
again to save.
B) The problem is that since we use ZFS, if a user has snapshots enabled,
they will just eat space for screenshots that aren't wanted.  Sometimes a
user will take multiple screenshots to get the layout just right, what you
are suggesting here will save multiple copies of the image to their home
dir which they may not want at all.

The reason applications like lumina-text-edit have the save warning and
lumina-screenshot doesnt is that doing another screenshot takes a few
seconds... retyping something will take much longer and you may not be able
to get the wording exactly correct.

Personally I dont think an OS should hold a users hand and warn them at
every turn if they dont do something.  But I'll leave this one to Ken to
decide.

Also your suggested file formats are exactly the same.

**Comment by grahamperrin** [comment]
Really, it's not pestering. 

> I'd get annoyed rather fast if … 

Imagine the annoyance caused by loss; when an unexpectedly discarded screenshot will be difficult or impossible to reproduce. 

> … your suggested file formats are exactly the same.

Nope, please take a second look :)

**Comment by q5sys** [comment]
I'm not sure I understand how someone could 'accidently discard' a 
screenshot.  Its not as if the application does anything else.  It's sole 
purpose it to make a screen capture.  If someone opens the program to 
capture a screen shot and then chooses not to save it... why would they be 
surprised by it not being saved?   Once you take a screenshot, the option 
to save it is immediately presented to the user.

**Comment by grahamperrin** [comment]
My first impression of this issue: the accident was made by the application, not the person. 

When Save As fails to save and the user is not warned that save failed, that seems (to me) like a bug.

**Comment by q5sys** [comment]
When does 'Save As' fail? I don't see anything in the code that would cause
such a thing to happen, so if that is happening I need to figure out why.
If you're talking about a situation where a user tries to save the file to
a location that they don't have write access too... that's not an
application failure, but a user failure.

**Comment by grahamperrin** [comment]
> user failure.

I doubt that we'll agree. I put myself in the shoes of users, maybe newcomers to TrueOS, who will have little or no knowledge of file systems, modes, ACLs and so on. 

----

Lumina Screenshot aside, for a moment: consider Insight, which offers the _(Limited Access)_ hint when the user browses to a directory where access is limited. Helpful features such as that should be welcomed.

**Comment by q5sys** [comment]
I'm deferring this one to Ken to make a decision on.

**Comment by BlazeTester** [comment]
I have an idea that could satisfy both of you:
In the "View/Edit" tab of Lumina Screenshot, one could add the hint "Screenshot hasn't been saved yet" in the line below the "Save As" button; and that this hint only disappears after a successful saving through the "Save As" button or with Phototonic.
(Though I don't know if Phototonic or an other program chosen as default screenshot editor can inform Lumina Screenshot about a successful saving).

This is also unobtrusive and useful for the case that I make a screenshot, don't save it, and make another screenshot immediately: here the next screenshot erases the former screenshot so that a warning would be necessary too - but a pop-up warning "Would you like to save the old screenshot?" would ruin the making of the next screenshot if I wanted to capture a time-critical event on screen.
(So a pop-up warning that covers all cases unobtrusively isn't possible anyway).

Alternatively Lumina Screenshot could create a Screenshot folder in the home directory of the user and autosave every screenshot to that folder.
But I would make such a function optional so that a user can switch it off or on by ticking an entry "Autosave to Screenshots folder in home directory" in a newly created "Option" menu next to Lumina Screenshot's "File" menu.

**Comment by BlazeTester** [comment]
Some more info about my sentence
"(Though I don't know if Phototonic or an other program chosen as default screenshot editor can inform Lumina Screenshot about a successful saving)."
from my last comment:

In the "View/Edit" tab of Lumina Screenshot, if I click on the "Launch Editor" button, the screenshot file is saved in the folder /Pictures. So one could think: "Now it's ok to remove the hint "Screenshot hasn't been saved yet" from Lumina Screenshot's "View/Edit" tab".
But if I choose "Delete" in Phototonic, this file is erased.
Therefore it would be necessary for Lumina Screenshot to notice such an erasure of the file by Phototonic so that it can show the hint "Screenshot hasn't been saved yet" again.
In the end I guess that the creation of such a functionality would be a bit too labor-intensive.
So I think the optional autosave alternative I mentioned in my last comment would be easier to create.

**Comment by beanpole135** [comment]
Basically I think this whole conversation boils down to one main issue:
When the screenshot fails to get saved when the user requests it (for some reason, such as no write permissions on the designated folder), the utility does not warn the user that the save routine failed.

I just fixed this in commit https://github.com/trueos/lumina/commit/61ec083ea62121a9eba88c4bd46f10be9b367f81

The screenshot utility is not designed for managing all of the users pictures, nor should it care what the user does with the screenshot file at a later date or in other utilities (that is where an app like phototonic comes in as a "manager" of the users image files). 
By the same token (and as q5sys already mentioned) more often than not people take multiple screenshots before they get one that is "just right" that they want to save - so automatically saving every screenshot into the user's "Pictures" directory (or anywhere else) is probably not a good idea because it basically adds more work on the user to keep their directories clear of unwanted files rather than only saving what the user wanted in the first place. Similarly, the autosave functionality will bypass any edits that the user wants to perform on the screenshot before saving it on the system, so that is another reason we should probably skip that option as well.

**Comment by grahamperrin** [comment]
Thanks. 

My viewpoints stem partly from the Mac tradition, learnt decades ago, of the computer saving without fail in response to a single action: Shift-Command-3. A shot with an _aural_ metaphor: the sound of the shutter of a camera. 

With Lumina there's the _visual_ metaphor of a camera, and I expect whatever's on the roll of film (or digital alternative) to be _kept, saved by default_ until I actively choose (at a later time or date) to discard selected items. One simple action: click. 

--- 

Call me old-fashioned :-)
