### ISSUE TITLE
The default panel should include the workspace switcher

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#318]
Two spaces by default so the GUI should offer an obvious means of using both. 

## Background

Since learning to key Control-F5 in Firefox, it's disconcerting when that key combination (with Lumina) causes disappearance of Firefox. 

That use case aside: simply, it should be good to make users more aware of the ability to switch.

**Comment by q5sys** [comment]
Ken and I have talked about a workspace switcher plugin before.  I dont know enough about the X backend to write one on my own. (I already tried).  
As for the key combo, I've been working on a list of sane keyboard shortcuts.  I'm aware of the keyboard shortcuts for Chrome and Qupzilla.  Can you get me a list of the ones in FireFox so I can make sure that I there arent any other collisions before I push the change?

**Comment by grahamperrin** [comment]
Thanks. The switcher does exist (https://bugs.pcbsd.org/issues/12373 improved use of icons, and so on), just not in a default panel. 

I'll seek information about Firefox …

**Comment by beanpole135** [comment]
As grahamperrin pointed out we have a workspace "switcher" panel plugin available, but q5sys is also right in that we do not have a workspace "pager" plugin yet.

The difference is that the "switcher" just lists the available workspaces in a menu and lets the user click an item to go to that workspace. This functionality is duplicated in a number of other panel plugins as well, including the start menu (Preferences -> Workspace) - which is why we did not add the workspace switcher plugin to the panel by default.

A workspace "pager" is somewhat similar, but shows a visual diagram/preview of every workspace including which apps are open on which workspaces, and clicking a preview takes the user to that workspace. This plugin does not yet exist for Lumina, but once it is created then I could see turning it on by default since it provides *additional* functionality that other plugins like the start menu do not have.

**Comment by grahamperrin** [comment]
Thanks, 

> start menu (Preferences -> Workspace) 

– I either never noticed that, or forgot that it existed.
