### ISSUE TITLE
Lumina Text Editor (lumina-textedit): Open File(s): Files of type: Text Files (*) selected, the dialogue shows other types

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#328]
![2016-12-18 21 34 30](https://cloud.githubusercontent.com/assets/192271/21321866/8d6f5942-c60e-11e6-8b84-23765ce70385.png)

**Comment by beanpole135** [comment]
This is intentional/needed. 
Plaintext files are used on systems all the time without giving them the ".txt" suffix (or any suffix for that matter - just look at "Makefile" or "/etc/rc.conf" for example). I needed to give the user the ability to specify *any* file, but still make it clear that it will treat all files as text files.
