### ISSUE TITLE
Lumina Text Editor support for composed (Control-Shift-U) entry of Unicode characters

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#329]
## Enhancement request

Lumina Text Editor does not support (for example): 

_Control-Shift-U 2026 Space_
– entry of … (the ellipsis character). 

With the application as it is, the keystrokes are interpreted literally so in lieu of 
'…' 
the result is 
'2026 '

## Information

[x11 - Is there a universal way to write Unicode characters? - Unix & Linux Stack Exchange](http://unix.stackexchange.com/q/185349/13260)

[compose key – Wikipedia](https://en.wikipedia.org/wiki/Compose_key)

**Comment by q5sys** [comment]
This is outside the scope of Lumina Text Editor.  This would need to be implemented on the Desktop level, and you would need some kind of middleware application that would actually capture the input, derive the appropriate unicode value and then pass that off to LTE.  The reason to do it this way is so that unicode would be available to every application and not just LTE.  Implementing it directly in one application would mean that every other application would also have to have this built in as well.  There's no reason to do that when this could be handled by a single utility.   

It's not a bad thing to have, but it's outside what Ken and I have time for.  Maybe put a request out to the community for someone to code this.  It shouldn't be too hard to code in QT.
