### ISSUE TITLE
Insight shows the wrong date of creation

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#336]
In this example, the file certainly was **not** created today (2016-12-24): 

![2016-12-24 03-48](https://cloud.githubusercontent.com/assets/192271/21465107/a18f4758-c98c-11e6-967a-0a0491a41a7a.png)

![2016-12-24-03-51](https://cloud.githubusercontent.com/assets/192271/21465108/c0e56326-c98c-11e6-85f5-794d7d3661e9.png)

**Comment by grahamperrin** [comment]
Incidentally, this bug might have reduced my ability to find what's required for other issues. 322 for example: 

> … a screenshot (it could be in any one of eight or more home directories across six notebooks …)

I often name files based on their dates of creation. If Insight or Lumina has misinformed me, it could be difficult for me untangle things.

**Comment by beanpole135** [comment]
Lumina just shows the created/modified timestamps from the filesystem itself. From the CLI you can check that Lumina matches the filesystem by running `ls -lh` within the desired directory.
Sometimes the creation date/time matches the modification date/time because of how the file was modified (a nuke/recreate instead of a load/modify), and other times it might be a filesystem flag or some other reason.

**Comment by grahamperrin** [comment]
Thanks. 

> … Sometimes the creation date/time matches the modification date/time … 

I'm puzzled by the highlighted file, which was _apparently_ not created until more than ten minutes after the file was modified. Is that logically possible? 

Yeah :-) this is exemplary of a report where I should have done more than highlight the apparent wrongness. Sorry!
