### ISSUE TITLE
Minimizing a window from the taskbar brings window of item to the left of the minimized item in the taskbar to front

### ISSUE THREAD

**Issue by ldemouy** [trueos/lumina#337]
Lumina Version: 1.1.2 (in TrueOS Stable, current as of last updates)
Preconditions:

* Multiple windows open (doesn't matter what program), two adjacent items in the taskbar open as opposed to minimized
* Have the item you want to minimize in the foreground and active
* Have the item to the left of the item you want to minimize as something other than the layer under the current active window, but open

Steps

1). Click in the taskbar to minimize the item
2). Move mouse off of taskbar (Bug does not occur until after mouse has left taskbar)

Expected behavior:
Window stacking is maintained, and the layer under the now minimized item is shown

Actual Behavior:
Item to the left of the item being minimized in the task bar is brought to the foreground, once mouse cursor leaves the taskbar.

**Comment by q5sys** [comment]
I've been trying to find a solution for you, but this is a fluxbox issue that we can't work around right now.  Once we switch to the upcoming Lumina WM, this should no longer be an issue.  
The problem is that Fluxbox keeps the window order (which you can access via Alt-Tab) internal and it's not exposed anywhere for us to link with.  As a result the panel has to use some order so it simply uses the order that the panel knows about... that being the left/right order of things present within it.
