### ISSUE TITLE
llvm39 required for compilation/build but not listed at DEPENDENCIES

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#340]
The most recent version https://github.com/trueos/lumina/blob/75303d3d2c6db7640bbbb4be283d578aef35e9a7/DEPENDENCIES was committed on 2016-06-23, probably before `llvm…` ceased to be within a standard installation of TrueOS Desktop.

**Comment by q5sys** [comment]
Clang is a compiler front end for the programming languages C, C++, Objective-C, Objective-C++, OpenMP,  OpenCL, and CUDA. It uses LLVM as its back end and has been part of the LLVM release cycle since LLVM 2.6.  

The way you install clang on TrueOS is by installing the llvm package. The following is taken directly from the llvm pkg info:
`This port includes Clang (a C/C++/Objective-C compiler), LLD (a linker), LLDB (a debugger), an OpenMP runtime library, and the LLVM infrastructure these are built on.`

It should be understood that in order to compile anything you need a compiling environment.  Clang needs llvm, gcc needs its RTL; both need the appropriate C librarys, linkers, etc.  I think it would be a bit too pedantic to start listing out every piece of entire tool chains.  The point of listing this is just to let people know they need to have a compiling environment installed, since there are many OSes that do not ship with a one installed.  

The reason Clang and GCC are the terms used in the Dependency list is because in general people discuss compiling environments by using the name of front end that you directly interact with.

**Comment by grahamperrin** [comment]
Sorry. I imagined a one-word addition to the DEPENDENCIES file.
