### ISSUE TITLE
A transparent panel can not be made opaque

### ISSUE THREAD

**Issue by grahamperrin** [trueos/lumina#347]
## Enhancement request

From [post 2](https://discourse.trueos.org/t/how-to-make-a-panel-opaque/376/2?u=grahamperrin) under _How to make a panel opaque?_: 

> … I think this was an option back in the early days of Lumina … Probably would be a good thing to file a feature request for. :slight_smile:

**Comment by beanpole135** [comment]
This is not reproducible.
There are currently no problems with "opaque panels". If you set a solid color without transparency on a panel you properly get an "opaque" panel. Same thing goes for switching to a desktop theme which does not use transparency for the panel appearance by default.

I think what you are referring to instead is that desktop icons/widgets can sometimes appear underneath a panel. This is currently caused by Fluxbox not properly adjusting the _NET_WORKAREA property when something like a panel reserves screen space using the _NET_WM_STRUT[_PARTIAL] property.

With the new Lumina window manager which is in development right now, we will be able to directly take responsibility for these properties and ensure that they are updated appropriately.

**Comment by grahamperrin** [comment]
> … I think what you are referring to instead …

No, that's a separate issue.

**Comment by q5sys** [comment]
>Probably would be a good thing to file a feature request for.

No need to file a feature request for something that's already existing.  It's been an option since probably the 0.8.2 release.

Lumina-Config > Appearance category> Theme Page> Desktop Theme tab > Theme Template Option

**Comment by grahamperrin** [comment]
The underlying issue is **wording**. Not all users of TrueOS Desktop will be able to guess that _alpha_ relates to opacity/transparency.
