### ISSUE TITLE
Can't shutdown on Slackware

### ISSUE THREAD

**Issue by sasongko26** [trueos/lumina#367]
I installed lumina by [SlackBuilds script](https://slackbuilds.org/apps/lumina) on slackware64-current from version 1.1.0, 1.1.0_p1 and 1.2.0_p1. The same problem : can't shutdown and reboot from menu, just exit from X. Does it require special configuration to shutdown or reboot via menu?

**Comment by beanpole135** [comment]
The shutdown options are contained within the LuminaOS compatibility layer: https://lumina-desktop.org/get-lumina/

Do you know which OS-interface the Slackware package is building with? It could be that one of the other "Linux" interfaces will work better on Slackware, otherwise you could create a new template for Slackware itself[1].

[1] https://github.com/trueos/lumina/tree/master/src-qt5/core/libLumina

**Comment by beanpole135** [comment]
Slackware is now recognized as a distinct Linux distro in the compatibility layer with a separate file/template.
Thanks for sending that in!
