### ISSUE TITLE
printing

### ISSUE THREAD

**Issue by mayerrs** [trueos/lumina#371]
hi,

i have this question. i tried to print in my new trueos. it works very well. but, i do have virtualbox now and i would like to print also from windows7 from virtualbox. can you help me how to do it? when i install the printer i checked "share this printer". and than i cannot find it or install this printer in windows in virtualbox. is here way to make it works?

thank you

**Comment by beanpole135** [comment]
This would be a problem with your VirtualBox configuration rather than Lumina.

If the printer is directly attached to the system (with a USB cable for instance), then you will probably need to setup the USB device passthrough for the virtual machine to be able to "see" it.
If it is a network printer, then you will need to make sure that your virtual machine can properly access the local network (network device passthrough?).
