### ISSUE TITLE
Changing default app not working

### ISSUE THREAD

**Issue by samob** [trueos/lumina#377]
I have noticed that changing default program for opening certain kind of files is not working as expected in Lumina. More info [here](https://discourse.trueos.org/t/changing-default-app-not-working/793).

**Comment by samob** [comment]
I have checked file permissions on .config directory and all looks good, but I noticed there is missing pathname in .config/lumina-mimeapps.list for the email and video I changed (tar is last in the list I did not change):

```
application/x-tar=/usr/local/share/applications/lumina-archiver.desktop;
application/email=thunderbird.desktop;
video/x-msvideo=smplayer.desktop;
```

**Comment by beanpole135** [comment]
The path for the default application is not required: If a relative path is given instead of an absolute path, then it scans the standard application registration directories to find the associated file (verified on my system).

Which version of Lumina do you happen to be using? Running `lumina-info` will give you that information. I am testing the latest builds obviously, but you might be running an older version which did not have that relative->absolute path adjustment routine.

**Comment by samob** [comment]
I have noticed this problem on previous build too, Lumina is 1.2.1, running on 12.0-CURRENT #23 27d3221(drm-next): Sun Feb  5, QT is 5.6.2
Strange thing, if run as root, lumina-info displays this:
`[root@trueos] ~# lumina-info 
QXcbConnection: Could not connect to display 
Abort
`

**Comment by beanpole135** [comment]
That error happens whenever you are not able to connect to the X11 display server (missing the DISPLAY env variable for instance).
If you need to run this from a terminal session rather than during a graphical session, run `lumina-desktop --version` instead.

**Comment by q5sys** [comment]
@samob Are you still having this issue on the latest sources?

**Comment by samob** [comment]
Actually it does not.
https://discourse.trueos.org/t/where-did-open-with-in-luminafm-gone-solved/1550/4?u=samob

**Comment by Mrt134** [comment]
It appears this issue is resolved now, from reading the discourse links. Please reopen or make a new issue if this is still a problem or becomes one again.
