### ISSUE TITLE
alt-f11 does not allow ending fullscreen nor alt-f4

### ISSUE THREAD

**Issue by markusalbertgraf** [trueos/lumina#385]
Windows like firefox and emacs can be brought into fullscreen with f11 (buildin command, not lumina command). Pressing f11 again brings them back from fullscreen.
But Windows that I switch to fullscreen with alt-f11 (lumina command) will not come back when I press alt-f11 again and can not be killed by alt-f4.

**Comment by markusalbertgraf** [comment]
Sending an alt-f11 fullscreen application to another monitor using alt-f3 kills or switches the desktop background image.

**Comment by grahamperrin** [comment]
Related (closed, lack of feedback from me): 

- [Feature #11685: the keyboard shortcut for full screen should be a two-way switch - PCBSD - Bug Tracking System](https://bugs.pcbsd.org/issues/11685)

**Comment by beanpole135** [comment]
This would be a Fluxbox issue since it controls the keyboard shortcuts, and any window actions like that.
In particular: I don't think Fluxbox provides a fullscreen window "toggle" action[1]. If you can find one, then we can easily add it to the default Fluxbox configuration for Lumina.

[1] http://fluxbox.org/help/man-fluxbox-keys.php
