### ISSUE TITLE
Feature request: lumina-screenshot rework

### ISSUE THREAD

**Issue by Mrt134** [trueos/lumina#394]
I've been playing with the latest iteration of lumina-screenshot, and I have a few suggestions for improvements:
1.  **Visible settings:** I appreciated the earlier version which had the settings visible with the view areas; it felt more concise and easy to just glance at the window (without having to switch tabs) to ensure I had the desired settings for my screenshot. I don't have strong feelings against the tabbed approach, but I think having the settings be always visible on the main window simplified the experience.

2. **Tabbed screenshots**: With the presence of the tab bar, would it be possible to have multiple (temporary) screenshots show up in the tabs? I think it could be useful to take screenshots in rapid succession and have them show up one by one as image1,image2, image3, etc. in the tab bar. Then I could bounce between each screenshot, close the ones I don't care for, and save the ones I want.

3. **Redundant "Close" button**: It seems a little redundant to have a close button in the UI when the minimize/fullscreen/close options are a few pixels above it. A quick review of the other lumina-utilities shows they only use the window options, with no "close" button in the UI (exception: lumina-search). For the sake of consistency, it would probably be best to align all lumina- utilities to either only use the minimize/fullscreen/close options or incorporate close buttons in the UI in the same relative position (currently upper right in -screenshot and lower left in -search.

**Comment by grahamperrin** [comment]
> Visible settings

+1

> Tabbed screenshots:

I imagine the interface becoming cramped, given what _appears_ to be a row of rectangular tab-like buttons, below the row of round buttons, in the same row as the first two tabs.  

> Redundant "Close" button

+1

**Comment by q5sys** [comment]
1) There is a push to keep the overall window size small, hence why Ken keeps putting tabs in when I pull them out.  :P  Also, as we increase the size of the overall window, the space available for cropping precisely becomes smaller.
2) https://i.memecaptain.com/gend_images/X5SlSQ.jpg  While technically feasible, due to the way we have the stacked widget this will get cluttered very quickly and you'll get a scroll area where the tabs are (think how tabs in browsers work when you have more than can fit the screen width).  This also will become more complicated and a mess if you have multiple unsaved tabs open and go to close the program.  Which ones are saved... which arent?  Do you give the user an announcement for each one, one bulk one that defines which tabs, ignore them all... I think you can see how this would get complicated real quick.
3) When I'm in office next week we need to have a pow-wow about gui design stuff like this.

I'm going to close this ticket for the moment, but we can hash this and other stuff out next week.
