### ISSUE TITLE
Lumina detects GPU acceleration - sometimes!

### ISSUE THREAD

**Issue by barulheira** [trueos/lumina#395]
Here: Intel machine, modesetting video driver, default settings (acceleration none).

Since I can't use PCDM (it crashes on Intel video driver), I start X and log into Lumina manually.

So, let's go:

Normally, when I log into Lumina, it logs to the console `Detected GPU Acceleration: false` as expected.

However, if I run `glxgears` _before_ logging into Lumina, it logs `Detected GPU Acceleration: true`! And then it starts compositing, and a `compton` process eats 5-10% CPU.

The same happens if I log out and then log in again to Lumina normally.

Is it correct?

**Comment by beanpole135** [comment]
This is an issue with glx on TrueOS/FreeBSD, and to work around it we have changed the logic for Lumina a bit so that compton is *disabled* by default unless the user enables the option to turn it on (there is also a separate option for enable + autodetect which can be toggled as needed).

This should fix the issues where we were getting "false positives" about GLX accelleration and instead shift the burden of enable/disable over to the user for the time being (with Lumina 2.0 we will be re-looking at the autodetection mechanisms since the compositing system is built-in to Lumina itself).
