### ISSUE TITLE
Desktop Entry Specification's StartupNotify=false seems ignored

### ISSUE THREAD

**Issue by mrijkeboer** [trueos/lumina#401]
When I start the `mount-cdrom.sh` shell script using the `mount-cdrom.desktop` file I get a busy cursor and the cursor remains busy. Only logging out and logging back in resets the cursor to normal.

However, when I place a call to `/usr/X11R6/bin/xmessage` before the `exit 0` in the shell script, the cursor returns to normal. So it seems that Lumina expects a window to show up before changing the cursor back to normal even though StartupNotify is set to false.

```
$ cat mount-cdrom.desktop                                                          
[Desktop Entry]
Version=1.0
Name=Mount CD-ROM
Comment=Mount a CD-ROM Drive
Exec=/usr/local/bin/mount-cdrom.sh
Icon=drive-optical
Terminal=false
Type=Application
Categories=System;
StartupNotify=false

$ cat mount-cdrom.sh                                                               
#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

doas mount /dev/cd0a $HOME/Media/CD-ROM

exit 0
```

- OS: OpenBSD-current AMD64
- Lumina: 1.2.0

**Comment by mrijkeboer** [comment]
The same thing seems to happen when I click the padlock icon in the menu to lock my screen. After unlocking my cursor remains in the 'busy' state. However, when the screen is locked due to a timeout the cursor is 'normal' after unlocking.

**Comment by Mrt134** [comment]
I can reproduce this with Lumina 1.3.2 on latest TrueOS UNSTABLE. Clicking the lock icon and logging back in forces the cursor into a "busy" state when hovering over the desktop, but not when using applications.

**Comment by beanpole135** [comment]
Done.
Lumina 1.x has never "fully" used that field from the XDG specs, because there are still so many cases where apps/tools are launched without a .desktop file. What I did was to disable the mouse cursor override by the session itself, and instead have a new "ExternalProcess" class which does a bit better job of how those extra processes get started/managed.

With Lumina 2 the application launching systems have actually been getting a much needed overhaul, and that system *does* respect the StartupNotify flag on .desktop files.

**Comment by beanpole135** [comment]
Forgot to include the link to the commit:
https://github.com/trueos/lumina/commit/af22aca563b822941825309b562379a01c84fba7
