### ISSUE TITLE
Regression - date/time issue

### ISSUE THREAD

**Issue by DmitryPostolov** [trueos/lumina#408]
Regression: after _clean_ install and to try set time/date format: hh:mm:ss and date for Saturday, 08 april 2017 no long words effect in string.

Workaround: delete last "s" in ss (hh:mm:ss) and type s again then press OK and all to be OK.

**Comment by q5sys** [comment]
I assume this is related to lumina-config -> General Options?
I need to know where to look to see what's going on.

**Comment by DmitryPostolov** [comment]
![10-23pm](https://cloud.githubusercontent.com/assets/20837310/25112285/4262603a-23be-11e7-9a01-d881c685f3b1.png)
![22-25](https://cloud.githubusercontent.com/assets/20837310/25112294/4bb8a6ee-23be-11e7-849e-c53216899112.png)
![22-26](https://cloud.githubusercontent.com/assets/20837310/25112302/5265c706-23be-11e7-8646-175b4c16a94c.png)
![22-27](https://cloud.githubusercontent.com/assets/20837310/25112318/5f4aa748-23be-11e7-804c-98a17dc0658f.png)

**Comment by DmitryPostolov** [comment]
Time/Date format for hh:mm:ss and ddd, dd MMMM yyyy Time first then Date will be set onle after delete last s in hh:mm:ss and type s again and press Save (OK) only from second time.

**Comment by q5sys** [comment]
ok, thanks for reporting back. I'll see what I can come up with in testing.

**Comment by q5sys** [comment]
I can confirm this behavior, but right now I'm not sure why the panel isn't updating.  I'll have to add in some debug functions and see if I can figure out what's going on.

**Comment by q5sys** [comment]
It looks like the issue is that when save is clicked, the setting is being set, the clock widget is getting the signal, but something is failing at that point.  You can change anything else, click save again, and then the clock will update.  (enabling numlockx for example)  So it's the result of being able to click save again which finally kicks the plugin to repaint.   
I dont see anything in the following that would account for this issue.
lumina/src-qt5/core-utils/lumina-config/pages/page_session_options.cpp
lumina/src-qt5/core/lumina-desktop/panel-plugins/clock/LClock.cpp

**Comment by DmitryPostolov** [comment]
q5sys, this problem is a regression: in one of the previous version of Lumina date/time settings can be set correctly from the first time.

**Comment by q5sys** [comment]
I understand its a regression. It's in your issue title. I wanted to check the code responsible for the actual implementation of the widget first and then work backwards over what's changed since it worked last.  My last post was a note in case someone else looked at it they could pick up from there.

**Comment by beanpole135** [comment]
Fixed!!

https://github.com/trueos/lumina/commit/58779ad78cf80423c8cf207fc72295b302fb2035
