### ISSUE TITLE
New material design icon theme impacts performance

### ISSUE THREAD

**Issue by word** [trueos/lumina#414]
The new 'material design' icon themes are impacting Lumina performance.  It's mostly noticeable during startup and when browsing applications in the 'start' menu.

On a clean install (in vbox) Lumina takes 22 secs to start with material design icon theme.  Once switched to adwaita it goes down to 6 secs.  It seems things start to slow down during the 'Preparing applications' stage.

In case of the 'Browse Applications' menu, it's most noticeable when 'Show Categories' is enabled.  When I click the 'Utility' category there is very noticeable delay (2-3 sec) before it opens.  The more applications in a category the slower it is.

On my laptop where I have many applications Lumina startup increased to almost a minute after the last TrueOS update, which was pretty unusable.  Switching to 'Adwaita' fixed it.

This should hopefully be straight forward to reproduce, but please give me a shout if you need any more info.

**Comment by beanpole135** [comment]
This has been fixed.
I had a couple special verification checks for detecting "bad" svg icons in the oxygen theme from a long time back, and since the new theme is all "good" icons (can be loaded by svglite standards) I went ahead and disabled those checks. This seems to make the icon/app startup routine back to normal (or even a bit faster than before since the svg icons are so much smaller than png icons).
