### ISSUE TITLE
Lumina under NetBSD

### ISSUE THREAD

**Issue by amoibos** [trueos/lumina#416]
I have played with Lumina 1.2.0p1 under NetBSD. It seems that Lumina looking for the resource file(oxygen icons) in /usr/local/share instead of /usr/pkg/share. Is there a variable which I can edit to fix the icon search path?

**Comment by beanpole135** [comment]
Since /usr/pkg/* is not part of the standard XDG search paths, you will just need to add that in to your environment variables before launching the desktop:
Something like this should work (in "~/.profile" or "~/.xprofile" for user settings, can't recall the exact file when starting X as root).
(NOTE: I am just adding the /usr/pkg/* dirs to the end of the standard paths - feel free to adjust as needed)
```
export XDG_DATA_DIRS=/share:/usr/share:/user/local/share:/usr/pkg/share
export XDG_CONFIG_DIRS=/usr/local/etc/xdg
```
I did not change the XDG_CONFIG_DIRS setting above - but wanted to include that just in case the pkgs are also expected to save their configs and such  into /usr/pkg/* instead of just /usr/* (you can change that manually as needed).
