### ISSUE TITLE
Switching workspace without key not possible

### ISSUE THREAD

**Issue by bcoolumbo** [trueos/lumina#436]
Under pure fluxbox this works with OnDesktop:
OnDesktop Mouse4 :PrevWorkspace
OnDesktop Mouse5 :NextWorkspace

**Comment by q5sys** [comment]
Yes, we changed the switch workspace macro because of conflicts, and adding the extra keystroke was the simplest solution for us.  We use:
# Control + MouseWheel to change workspaces
Control Mouse4 :PrevWorkspace
Control Mouse5 :NextWorkspace

But obviously, as you state, that requires a keystroke.  We're going to be moving away from Fluxbox in the future, so we're doing as little as possible configuring FluxBox at this point.  Sorry.
