### ISSUE TITLE
Use OnlyShowIn=X-Lumina in .desktop files

### ISSUE THREAD

**Issue by charIes17** [trueos/lumina#447]
Gentoo dislikes "OnlyShowIn=Lumina" in .desktop files.
Instead, it wants "OnlyShowIn=X-Lumina"

See https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-wm/lumina/files/1.2.0-desktop-files.patch
Discussion on https://forums.gentoo.org/viewtopic-p-8084278.html

**Comment by q5sys** [comment]
hmmm, your patch will fix it for Gentoo, but unfortunately it will break it for every other linux distro that requires "OnlyShowIn=Lumina".  I think that should be something you guys patch in the ebuild since it seems to be specific to Gentoo.  Sadly there is no way to do ifdef's in .desktop files. 

Are you aware of any other Gentoo issues we might be able to fix upstream for you guys?

**Comment by charIes17** [comment]
Please see my comment on OS-detect.pri
@@ -76,6 +76,11 @@
     equals(LINUX_DISTRO,"Fedora"){
       isEmpty(L_ETCDIR){ L_ETCDIR=/etc }
     }
+    equals(LINUX_DISTRO,"Gentoo"){
+      isEmpty(L_BINDIR){ L_BINDIR = $${PREFIX}/bin }
+      isEmpty(L_ETCDIR){ L_ETCDIR = $${PREFIX}/../etc }
+      isEmpty(L_MANDIR){ L_MANDIR = $${PREFIX}/share/man }
+    }
   }else{

**Comment by q5sys** [comment]
I'll get these taken care of tonight. Thanks for letting us know what's needed.

**Comment by charIes17** [comment]
Thanks in advance.  One more thing would be updating the "lumina-9999.ebuild" according to https://github.com/trueos/lumina/compare/master...charIes17:patch-1

**Comment by beanpole135** [comment]
@all: This is not a bug in Lumina, but rather a bug in the .desktop validator utility you are using. The "Lumina" value for only-show-in is valid and adheres to the XDG specifications, but your validator tool is only looking for a hard-coded list of "known" desktops which does not include Lumina or some other DE's I am aware of.

This has been brought up before, and after some discussion I believe the OP submitted a patch upstream to the validator he was using. You might need to do something similar on Gentoo or see if there is a newer version available.

FYI if you change that value to X-Lumina, you will effectively hide it from ALL desktops because that will no longer match the "Lumina" registration that the desktop supplies.

**Comment by beanpole135** [comment]
Another solution would be to bypass/ignore the .desktop file validator you are using in the ebuild process. I just looked at your forum thread and those other errors listed regarding categories for Link-type files are also erroneous - while categories are required for application-type files, they may be optionally used or ignored for other types of files at the DE's discretion. Lumina supports category listings for all types of .desktop files (how else can you find a web-based application which is installed on the system?), but other DE's should just ignore that field in the file if they don't support it.

**Comment by q5sys** [comment]
Extra Gentoo specific variables set.  
https://github.com/trueos/lumina/commit/082488bf713da32103ac64fedea7f19ac2aa1e30
