### ISSUE TITLE
Separate tarballs / tags for core and utilities

### ISSUE THREAD

**Issue by charIes17** [trueos/lumina#454]
As a gentoo user I would like to see separate tarballs / tags for 
lumina-core

lumina-config
lumina-search
lumina-xconfig

lumina-screenshot
lumina-fileinfo
lumina-textedit
lumina-calculator
lumina-archiver
lumina-mediaplayer
lumina-xdg-entry

**Comment by q5sys** [comment]
Thanks for the ticket.  We'll talk this over and see if this is something we might consider.

**Comment by beanpole135** [comment]
I have been looking into this and I don't think this is something we will be doing anytime soon for a couple reasons:
1. The GitHub release process always makes a single tarball for the repo - splitting this up will require a ton of extra effort to write custom release procedures.
2. All the Lumina tools use a number of common files, which is why all the tools have the same version number and the source tree is arranged this particular way. Splitting up the tools means also making copies of those files for each tool and breaking how easy it currently is to maintain/update everything at the same time.

Possible Solution:
It looks like the individual tarballs are not the main point - but rather you want individual packages for each utility. This can already be done: just look at the FreeBSD port-file directory for an example.  Here is a quick summary of the steps though:
1. Download the source tarball (your package utility should be smart enough to re-use the one tarball for all the Lumina ports/packages - so you only fetch it once).
2. Change to the directory of the utility that you want to build. Examples: "src-qt5/core" for lumina-core, "src-qt5/desktop-utils/lumina-calculator" for lumina-calculator, etc....
3. Run the normal build processes (qmake, make, make install)

**Comment by irelativism** [comment]
Indeed the separation would be nice. I think the question is more why not make that on website instead of gatehub

Cheers regardeless for feedback
