### ISSUE TITLE
lumina-fm: Change (colour of) preview zoom icons, add shortcuts and menu items

### ISSUE THREAD

**Issue by danboid** [trueos/lumina#459]
I recently created a ticket requesting lumina allow you to adjust the size of image preview thumbnails. The ticket was closed because lumina already has this feature but there is a good reason I didn't see it and that's because the zoom icons are almost invisible when using the TrueOS default Qt theme which is rather light in shade and this makes the icons nigh-on invisible. Simply changing the colours of the + and - symbols on the icons to something like black or red would fix this.

It would also be good to add zoom in and zoom out options to the View menu and add default keybindings to both like CTRL_+ and CTRL_- .

**Comment by beanpole135** [comment]
Icon/Theme Colors:
This has already been fixed in the latest version in source (or on the UNSTABLE TrueOS repository). With the new lumina-theme-engine, we are able to automatically turn on particular themes for both the desktop and the applications so there is a more unified appearance out-of-box.

Ctrl-[+/-] Shortcuts:
I don't think we have these shortcuts setup yet for lumina-fm, should be an easy fix.... :-)

**Comment by q5sys** [comment]
I've increased the size of the icons a bit so they stand out more.  They will use whatever icon theme you are using, so make sure you pick an icon theme that shows up well with your current theme template.
Ctrl +/- should already work.
https://github.com/trueos/lumina/blob/master/src-qt5/desktop-utils/lumina-fm/widgets/DirWidget2.cpp#L234

**Comment by q5sys** [comment]
If you run into any problems with this feel free to re-open the ticket.

**Comment by danboid** [comment]
The icons are much more visible now. Thanks!
