### ISSUE TITLE
Not all icons available in Lumina panels

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#468]
Some icons are shown correctly, others are not. See panel screenshot.

![screenshot-panel-icons](https://user-images.githubusercontent.com/3322553/30985232-00a0832c-a490-11e7-9e62-346780e9e9af.png)

When checking /usr/local/share/applications it makes a difference whether I am running Lumina-FM as root or as a normal user. When run as the latter the exact same icons that display correctly in the panel are the only ones shown as images in Lumina-FM. When run as root, all icons are displayed in Lumina-FM.

Lumina-FM run by normal user:
![lumina_app_icons_user](https://user-images.githubusercontent.com/3322553/30985473-8422ec30-a490-11e7-91e4-4eeb1038a583.png)

Lumina-FM run by root:
![lumina_app_icons_root](https://user-images.githubusercontent.com/3322553/30985492-997cb688-a490-11e7-8f56-1b4ed0ee1a0a.png)

**Comment by q-pa** [comment]
There is also difference in the directory icons in the directory tree for root/user, as you can see.

**Comment by Mrt134** [comment]
This may be completely unrelated, but I had an issue similar to this after the last update. I was previously testing the `qt5ct` theme engine and, after updating, Lumina continued to load/point to that instead of the Lumina theme engine as the new default. Have you made any adjustments/customisation in theming that could be conflicting with what Lumina is trying to do by default?

Regardless, thanks for the report and I'll try and see if I can reproduce!

**Comment by q-pa** [comment]
This issue turned up when I switched to UNSTABLE end of August. I don't think that Lumina is looking in the wrong directory. All icons are there, Lumina just cannot see them all. Seems to be related to the Lumina-FM normal user/root issue described above. I already ran the desktop settings as root and added a program to the panel which icon only shows correctly in root-Lumina-FM but that did not solve it.

**Comment by q5sys** [comment]
What are the file owner/group and permissions on the icons?

**Comment by q-pa** [comment]
Hm, I don't see why e.g. the Darktable icon is displayed correctly and the Firefox icon is not.

`ls -l /usr/local/share/applications
total 162
-rw-r--r--  1 root  wheel    233 25 Aug. 17:13 appcafe.desktop
-rw-r--r--  1 root  wheel    938 17 Sep. 17:35 audacity.desktop
-rw-r--r--  1 root  wheel   8971 17 Sep. 03:27 bonobo-browser.desktop
-rw-r--r--  1 root  wheel    323 17 Sep. 01:33 chromium-browser.desktop
-rw-r--r--  1 root  wheel    216 17 Sep. 04:21 compton.desktop
-r--r--r--  1 root  wheel   2069 16 Sep. 23:46 cups.desktop
-rw-r--r--  1 root  wheel   3468 17 Sep. 19:10 darktable.desktop
-rw-r--r--  1 root  wheel   1049 17 Sep. 21:06 FBReader.desktop
-rw-r--r--  1 root  wheel   6545 17 Sep. 02:16 firefox.desktop
-rw-r--r--  1 root  wheel   5550 17 Sep. 02:02 gcr-prompter.desktop
-rw-r--r--  1 root  wheel    690 17 Sep. 02:02 gcr-viewer.desktop
-rw-r--r--  1 root  wheel   2085 17 Sep. 16:49 geeqie.desktop
-rw-r--r--  1 root  wheel    216 16 Sep. 23:54 geoclue-demo-agent.desktop
-rw-r--r--  1 root  wheel    329 16 Sep. 23:54 geoclue-where-am-i.desktop
-rw-r--r--  1 root  wheel  11456 17 Sep. 04:58 gimp.desktop
-rw-r--r--  1 root  wheel    318 17 Sep. 18:42 gpodder-url-handler.desktop
-rw-r--r--  1 root  wheel   4122 17 Sep. 18:42 gpodder.desktop
-rw-r--r--  1 root  wheel    421 18 Sep. 05:40 gscan2pdf.desktop
-rw-r--r--  1 root  wheel    201 16 Sep. 23:59 gtk3-demo.desktop
-rw-r--r--  1 root  wheel    221 16 Sep. 23:59 gtk3-icon-browser.desktop
-rw-r--r--  1 root  wheel    246 16 Sep. 23:59 gtk3-widget-factory.desktop
-rw-r--r--  1 root  wheel   3623 17 Sep. 10:08 gvim.desktop
-rw-r--r--  1 root  wheel   1681 17 Sep. 09:42 handbook.desktop
-rw-r--r--  1 root  wheel    347 17 Sep. 14:51 hplip.desktop
`

**Comment by q5sys** [comment]
Well there is the reason why, those icons are owned by root.  A regular user is unable to access them.  You need to resolve the screwed up permissions issues in your system.  This will continue to cause issues on your system until these are set correctly.  The ones that are working may be due to there being another copy of the icon available in your system that is not owned by root.

I would recommend re-installing and then migrating your user directory over to the new install.

What you are experiencing is not a bug... it's proper user restrictions working correctly.

**Comment by q-pa** [comment]
I am sure I did not willingly change any permissions. And changing the owner did not solve this. 

I checked with a Virtual Box installation of UNSTABLE and there I found the exact same permissions. I also checked with an old PCBSD 10.3 system: also owner root. 

Did you try to set up a secondary panel with e.g. a Firefox application starter?

However, I will perform a fresh reinstall as soon as GELI full disk encryption works again. Maybe something else is broken with my system.
