### ISSUE TITLE
Roll over video playback

### ISSUE THREAD

**Issue by JohnHolmes69** [trueos/lumina#476]
Similar to Youtube, requesting the roll over play request

As soon as the mouse rolls over any video, plays begins

**Comment by ZackaryWelch** [comment]
Thanks for the feature request! This idea fits easily into the current framework and can probably be done pretty soon.

**Comment by danboid** [comment]
What would be extra cool would be if there was a way to extend this feature so that the user could set the thumbnail of video files to a custom image (a still from within that video file) to replace whatever lumina-fm created as the default thumbnail.

Maybe something like this as an example workflow:

* Hold down ALT key
* Mouseover video file - video preview begins
* Left click the video icon whilst still holding ALT key and the thumbnail gets updated with whatever frame is being played at the time of the click.

**Comment by ZackaryWelch** [comment]
This feature is currently implemented in lumina-fileinfo. We are looking to expand this to the file manager once the bugs can be ironed out. Custom thumbnails are also an interesting idea that is possible with the current framework. We will look into it.
https://github.com/trueos/lumina/commit/cd928a79ff4bf6da55689bc100168355ec962b50

**Comment by danboid** [comment]
Great news!

**Comment by ZackaryWelch** [comment]
Finished. When you mouse over the video, the video will start playing at 3x speed until your mouse leaves the thumbnail area.
https://github.com/trueos/lumina/commit/3a38773ce20620610e87c84c40ebfd6d2f478203
