### ISSUE TITLE
[doc] Linux support?

### ISSUE THREAD

**Issue by shevegen** [trueos/lumina#496]
Hey guys,

Could the main README mention whether lumina supports linux?

I assume so, but perhaps there may be some caveats or such.

**Comment by q5sys** [comment]
Thanks for the ticket.  Currently the ReadMe states:

> The Lumina Desktop Environment is a lightweight system interface that is designed for use on any Unix-like operating system. 

Since Linux is a Unix-like Operating system, we thought this was covered, but I guess we can go in and make it more specific.  The problem is that once we start naming 'some' Unix Like Operating systems, If we don't list all of them then people may believe that Lumina wont run on them.  That's why we chose to write 'Unix Like'.

However, all that being said, we will talk it over and see if we can come up with a better way to explain it.  Thanks for letting us know it's not completely.

**Comment by beanpole135** [comment]
Done!

https://github.com/trueos/lumina/commit/1b2959737e8ee8ad79a8b7fed981363aae05b103
