### ISSUE TITLE
Desktop image is treated like window

### ISSUE THREAD

**Issue by jw2249a** [trueos/lumina#500]
if I press ALT and click the desktop my Wallpaper will move off my screen. Not super big but just a heads up.

**Comment by ZackaryWelch** [comment]
I have tested this on TrueOS stable with the most recent revision of Lumina 1.33 and it is confirmed. The desktop "window" is not supposed to respond to the fluxbox alt+L/R click, so this is definitely a bug, and a recent one at that.

**Comment by beanpole135** [comment]
This was something that was fixed a while back, but the fix could not be forcibly pushed out to everybody because it is a line buried in your personal Fluxbox configuration file.

Basically the fix is this:
Open up `lumina-config` and browse to the "Desktop Defaults" -> "Keyboard Shortcuts" page, then click on the "Advanced Editor" (or just open a text editor on your "~/.config/lumina-desktop/fluxbox-keys") file.

Once there, look for the line that starts with "OnWindow Mod1 Mouse1" or "OnWindow Mod1 Mouse3" and change them to match this:
```
OnWindow Mod1 Mouse1 :If {Matches (Layer=Normal)} {MacroCmd {Raise} {Focus} {StartMoving}}
OnWindow Mod1 Mouse3 :If {Matches (Layer=Normal)} {MacroCmd {Raise} {Focus} {StartResizing NearestCorner}}
```

That tells fluxbox to only allow the Alt + mouse button shortcuts on "normal" windows - and not on things like the desktop, fullscreen windows, splashscreens, and more.
