### ISSUE TITLE
lumina-1.4.0: ctrl-q no longer works in qpdfview

### ISSUE THREAD

**Issue by grozin** [trueos/lumina#517]
After the upgrade to 1.4.0, when I start qpdfview and then press ctrl-q, nothing happens. qpdfview is the current snapshot configured with Qt5. In lumina-1.3.0 patchset 1 I could quit qpdfview by pressing ctrl-c.

**Comment by beanpole135** [comment]
Probably because you are no longer using qpdfviewer... :-)
qdfviewer is a completely separate, 3rd-party application that TrueOS installed out-of-box quite a while back, but in recent times that package no longer builds properly on FreeBSD (port has been broken for about 2-3 months now) and we moved to a new default application called "lumina-pdf". Since lumina-pdf is still so new, we are still missing some of the niceties that have existed in more mature applications, but we are gradually adding in them in as time goes on (keyboard shortcuts for lumina-pdf were actually just committed a couple days ago if I recall correctly).

**Comment by grozin** [comment]
No, I use qpdfview, the current snapshot, configured it with qt5 and compiled myself. I'm on Gentoo Linux (btw, I'm the maintainer of the lumina package in Gentoo, have just committed 1.4.0 patchlevel 1). The same qpdfview binary works as expected in lumina-1.3.0 patchlevel 1; in 1.4.0 it also works, but ignores ctrl-q. Seems mysterious. Does lumina-1..4.0 intersept ctrl-q in any way?

When I start qpdfview (and many other programs), I get

lthemeengine: using lthemeengine plugin
lthemeengine: D-Bus global menu: no

These programs work normally in spite of these messages, only qpdfview ignores ctrl-q.

**Comment by beanpole135** [comment]
Ok, that must be something in qpdfview then. The Lumina theme engine is just a style plugin for the application instance and does not touch anything related to input management. 
It is also possible to setup Fluxbox to intercept the Ctrl-Q shortcut and have it close the currently-active window (usually closing the application). That will work across all applications/windows (not just Qt5 applications).
