### ISSUE TITLE
Session file missing DesktopNames field

### ISSUE THREAD

**Issue by cpforbes** [trueos/lumina#520]
The session file `src-qt5/core/lumina-desktop/Lumina-DE.desktop` should include a `DesktopNames` field.

Login managers are supposed to use the value in that field to set the environment variable `XDG_CURRENT_DESKTOP`

It is poorly documented here https://specifications.freedesktop.org/desktop-entry-spec/1.1/ar01s05.html
In the description of the "OnlyShowIn, NotShowIn" fields for some reason.

**Comment by cpforbes** [comment]
It looks like the freedesktop.org specs include a list of valid names:
https://standards.freedesktop.org/menu-spec/latest/apb.html

It would be nice to get Lumina on that list.

**Comment by beanpole135** [comment]
The XDG_CURRENT_DESKTOP environment variable is supposed to be set at the outset of the desktop launching (not necessarily by the DM). That is one of the first things that happens when the "start-lumina-desktop" procedure is launched (either by the user, or by a DM).

The "DesktopNames" field does not exist in any of the specs at the present time. That one reference to it in the desktop-entry spec (as an off-hand comment for a different field) actually appears to be a left-over that they forgot to remove when they were considering the addition of a "DesktopNames" field (or a leftover when they removed the DesktopNames field - not sure which came first).
Just thinking about it, the XDG_CURRENT_DESKTOP field **needs** to contain a unique ID for each of the different desktops. If the DM is supposed to set that field before login, then it needs the **unique id** for the desktop, not a list of possible names. That might be why the "DesktopNames" field does not officially exist right now - they might still be working through the logic of how/when it is needed.

As for getting Lumina on the FreeDesktop "menu-spec" list - please send in the request to the FreeDesktop/XDG group itself. Every time I try to contact them I just get ignored, so perhaps if other people also send them messages something might get done.

NOTE: A hard-coded list of desktops is actually not supposed to be used for any of the menu-spec fields. Instead, you are supposed to simply match the XDG_CURRENT_DESKTOP value to the list and see if it matches. Some kind of pre-determined list of "valid" names is completely unnecessary.

**Comment by cpforbes** [comment]
According to this bug: https://bugs.freedesktop.org/show_bug.cgi?id=85938 the comment under OnlyShowIn is the documentation for the DesktopNames field.

Inexplicably they seem to think that is adequate.

**Comment by beanpole135** [comment]
According to that email chain, there apears to be no specifications regarding the xsession files at all: It is a loose concensus among the various DM's to use the desktop entry spec as the basis. In any case, since Lumina already sets the XDG_CURRENT_DESKTOP field on startup, I don't see any need to adjust our xsession file at the moment. If you can point to some particular DM's that ignore the Lumina xsession file because of "missing" that field, then I suppose we could make that change.

**Comment by cpforbes** [comment]
The only potential issue is that the XDG_CURRENT_DESKTOP environment variable will not be set by the DM but that seems to be covered by Lumina setting it itself.

I feel for you trying to implement a desktop environment -- the "specifications" on freedesktop.org are barely adequate. It seems like they might as well say "read the Gnome source code."
