### ISSUE TITLE
Bad Quality of Lumina-PDF Viewer (compared to TrueOS PDF Viewer)

### ISSUE THREAD

**Issue by q-pa** [trueos/lumina#528]
The quality of displayed text in Lumina PDF viewer is really bad compared to the old TrueOS PDF viewer. I am seeing this on my fresh install of STABLE and in an updated UNSTABLE installation as well. These are the according screenshots.

Lumina PDF viewer:
![lumina-pdf](https://user-images.githubusercontent.com/3322553/34270129-65c63e7a-e687-11e7-8a81-d98a2fcac009.png)

TrueOS PDF viewer:
![trueos-pdf](https://user-images.githubusercontent.com/3322553/34270140-6f3a8312-e687-11e7-99d2-03ef168ef38a.png)

**Comment by q5sys** [comment]
Thanks for the bug report.  We'll look into this.  I know Zack is doing some work on it at the moment, so maybe he'll be able to squash this on while he's in turning the wrenches. :)

**Comment by ZackaryWelch** [comment]
Lumina-pdf is being rewritten. On top of adding new features, we are changing how the pdf is displayed. Currently we were displaying each page as an individual image, but for higher resolutions this takes a lot of memory. We have to cache each page in order to avoid high CPU usage when moving up/down, but in order to do that each page has to be kept at a low resolution. Especially for text pages, this creates bad quality. Hopefully soon a rewrite will be pushed that displays crystal clear text and only caches images on the pdf, as opposed to an image of the pdf, but that might take a while.

**Comment by q-pa** [comment]
Thanks a lot (also for explaining the background)!

**Comment by beanpole135** [comment]
High-quality image rendering has already been committed to lumina-pdf (currently version 1.4.2).
