### ISSUE TITLE
[Feature request] style of lumina-fm

### ISSUE THREAD

**Issue by jwvdveen** [trueos/lumina#546]
Lumina-fm has thick borders inside the main window. While going through the source of Lumina, I found the layout margins and spacings weren't set. 

To me this seams like a waste of space, but perhaps there is a reason for doing it so?

Now, these values can't be changed through style sheets. So, would it be an idea to make them customizable some other way?

**Comment by q5sys** [comment]
Ken and I were talking about this last week actually.  We were planning on making the padding a bit smaller.  We have some heavy work under the hood to do on the file manager in the future, but that's been pushed back due to focusing on the upcoming window manager.  So we were planning on getting around to it when we dug back into the code.  There are also a few features which are not graphically exposed yet due to not being finished, but that should not be causing any extra spacing.

**Comment by jwvdveen** [comment]
Well, no hurry ofcourse.
I was playing around with the source code and found some possible BoxLayouts which could do the trick. So, if I can help...

**Comment by beanpole135** [comment]
Done!
https://github.com/trueos/lumina/commit/00853a147b1d5f81fe13e5a69af199a3d1c763ac
