### ISSUE TITLE
How to launch Start Menu, when Win/Super key is pressed?

### ISSUE THREAD

**Issue by signal-tenet** [trueos/lumina#553]
How could I assign a key, to launch Start Menu,  when Win/Super key was pressed? Same as in Windows?

**Comment by q5sys** [comment]
hmm... it was my understanding that this was already done.  It works for me.  We actually have three start menus available.  can you take a quick screenshot so I can figure out which one you are using.  Also, what OS is this on?  TrueOS or another BSD or Linux?

**Comment by signal-tenet** [comment]
I'm using Fedora OS 27, with Lumina 1.4.2
![selection_001](https://user-images.githubusercontent.com/17032837/36962584-d1ac3d14-2058-11e8-91c7-c6eb85ac5e5a.png)

**Comment by beanpole135** [comment]
The home/windows key shortcut is already pre-set with Lumina since version 1.0 or similar (X11 key# 115).
You might want to check if keyboard is sending keycode 115 for your windows key. You can easily do this by installing the "xev" utility, run it, and then hit the windows key to see all the information associated with that key press/release event. If your key is associated with a different key number, just change the following line in your keyboard shortcuts (advanced view in lumina-config, or directly edit "~/.config/lumina-desktop/fluxbox-keys"):
```
115 :Exec lumina-desktop --show-start
```
Replace the "115" with whatever key code your system is using for the windows button.

**Comment by signal-tenet** [comment]
Thank you very much. Now it's working. My keycode was 133, after changing it - it's working fine.
